/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package GradleDemoProject;

public class Library {
    public static void main(String[] args) {
		System.out.println("hii");
	}
}
